version: '3.8'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    image: qadasolat/front
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: unless-stopped